/* eslint-disable @typescript-eslint/no-unused-vars */
import { JWT_KEY } from '@constants'
import jwt, { JwtPayload } from 'jsonwebtoken'
import { TokenGenerationPayload } from 'types'

const verifyJWT = (token: string): JwtPayload => {
  return jwt.verify(token, JWT_KEY) as JwtPayload
}

const createJWt = (data: TokenGenerationPayload, expiryTime: number) => {
  return 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJsYmJUcDRObzdfUHBJLUxOWFZJbUFmY1pWQWs3TFNwdnY5Z0RFVF80M2ZrIn0.eyJqdGkiOiJiMmVmNmU2Ny04OWI0LTRiOTctYTMxNS0xMWU4NzI2MzYxYzYiLCJleHAiOjE2NzAzNjc2MTgsIm5iZiI6MCwiaWF0IjoxNjcwMzMxNjE5LCJpc3MiOiJodHRwczovL2F1dGguY2xvdWQuZGF0YXN0YXguY29tL2F1dGgvcmVhbG1zL0Nsb3VkVXNlcnMiLCJhdWQiOiJhdXRoLXByb3h5Iiwic3ViIjoiOTRkMTQzNDMtYWYzYy00MjVlLThiMjctNGEyZjU2YzBkMDZiIiwidHlwIjoiSUQiLCJhenAiOiJhdXRoLXByb3h5IiwiYXV0aF90aW1lIjoxNjcwMzMxNjE4LCJzZXNzaW9uX3N0YXRlIjoiNTk5MzgxYmQtOTUwZC00NmEzLWFjNWQtMzc5YzQ3MTRjYmIzIiwiYWNyIjoiMSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwibmFtZSI6ImFkZWVsIGJ1dHQiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZGVlbEB0cmltdWxhYnMuY29tIiwiZ2l2ZW5fbmFtZSI6ImFkZWVsIiwiZmFtaWx5X25hbWUiOiJidXR0IiwiZW1haWwiOiJhZGVlbEB0cmltdWxhYnMuY29tIn0.HII5q1EYQB67x760N26sC0n84v8Y6bGUoLsD3jXQNXYxEVatbubXY7Rd-6dl6_ugeEYHXw8j_6IzX_uLHwqwfPTSRZueCT-undjl2T3L52h-BWOcH2z7LlR5o7j2LlTVcLBfzkPQyoiyhArjXDKq1bq6b0X2IEV6Xw-ljoJxNhOUzDJnO3ooWbqScyKxtAnFdsD_fwVoYAfbqgG0jog7-xqG2tDtqU63yF0E8p_LhJkQvjy6vnlqBXhPSuKE4cXOs1o2FxHsUd9V5siqB8k1Prz6U_N6g7R-R9VbmeI8GY4Y1y0YBYeA0QGWazQOVmku8ipNA8fUAzoQmT_siZkWLg'
  // return jwt.sign(data, JWT_KEY ?? '', {
  //   expiresIn: expiryTime,
  // })
}

export { verifyJWT, createJWt }
